---
title: "LIBER"
author: "Leo Lahti"
date: "23/10/2015"
output: markdown_document
---

```{r summaryinit, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr)
library(bibliographica)
library(estc)
df <- read.csv(file = "estc.csv", sep = "|")

# Order the levels where necessary
df$gatherings.original <- order_gatherings(df$gatherings.original)
df$gatherings <- order_gatherings(df$gatherings)
df.preprocessed <- df
```

```{r, echo=FALSE, message=FALSE}
library(rmarkdown)
library(knitr)
library(ggplot2)
library(estc)
library(bibliographica)
opts_chunk$set(cache=TRUE)
library(dplyr)
library(ggthemes)
#ggplot_set(theme_bw(20))
df <- df.preprocessed
df <- df[-which(df$publication_year < 1470),] 
```


```{r 20151023LIBER-1, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=6}
library(ggplot2)
library(dplyr)
theme_set(theme_bw(50))
selected.authors <- c("prynne, william (1600-1669)", "defoe, daniel (1661-1731)", "hume, david (1711-1776)", "hume, david (1560-1630)")
top <- names(rev(sort(table(df$author_unique))))[1:20]
top <- c(top, "hume, david (1560-1630)")
top <- setdiff(top, "caesar, julius (-100- -44)")
dfs <- filter(df, author_unique %in% top)
p <- top_plot(dfs, "author_unique", ntop = 30, highlight = selected.authors)
p <- p + guides(fill = "none")
p <- p + ylab("Title count")
p <- p + scale_fill_manual(values = c("darkgray", "black"))
print(p)
```

```{r 20151023LIBER-2, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=7}
theme_set(theme_bw(20))
dfa <- dfs[, c("author_name", "author_unique", "author_birth", "author_death")]
dfa <- dfa[!duplicated(dfa), ]
#dfa <- dfa[match(names(a), dfa$author_name),]
dfa <- arrange(dfa, author_birth)
# Order authors by birth year
dfa$author_name <- factor(dfa$author_name, levels = unique(dfa$author_name))
dfa$index <- sample(factor(1:nrow(dfa)))
dfa$fill <- rep("black", nrow(dfa))
dfa$fill[dfa$author_unique %in% selected.authors] <- "red"

p <- ggplot(dfa)
p <- p + geom_segment(aes(y = author_name, yend = author_name, x = author_birth, xend = author_death, color = fill), size = 2) 
p <- p + theme(axis.text.y = element_text(size = 14))
p <- p + xlab("Author life span (year)") + ylab("")
p <- p + guides(color = FALSE)
p <- p + scale_color_manual(values = c("darkgray", "black"))
print(p)
```


```{r 20151023LIBER-3, echo=FALSE, message=FALSE, cache=FALSE, fig.height=4, fig.width=10}
theme_set(theme_bw(20))
dfs <- df %>%
         filter(author_unique %in% selected.authors) %>%
	 group_by(author_unique, publication_year) %>%
	 tally() %>%
	 arrange(publication_year)
theme_set(theme_bw(20))

# Barplot version
p2 <- ggplot(dfs, aes(x = publication_year, y = n, fill = author_unique)) +
       geom_bar(stat = "identity", position = "stack") +
       xlab("Publication Year") +
       ylab("Title Count")       
p2
```


```{r 20151023LIBER-3b, echo=FALSE, message=FALSE, cache=FALSE, fig.height=7, fig.width=7}
library(tidyr)
dfs <- df

top <- names(rev(sort(table(df$author_unique))))[1:20]
top <- c(top, "hume, david (1560-1630)")
top <- setdiff(top, "caesar, julius (NA-NA)")
topa <- top

# 2long/2fo/2small -> folio; 8vo -> octavo
dfs$gatherings <- harmonize_names(dfs$gatherings, gatherings_table(),
	       	  		from = "Standard", to = "Name")$name

dfs <- dfs %>% filter(author_unique %in% top &
	        gatherings %in% c("folio", "octavo")) %>%
	 group_by(author_unique, gatherings) %>%
	 tally() %>%
	 spread(gatherings, n)
dfs$highlight <- dfs$author_unique %in% c(selected.authors, "burke, edmund (1729-1797)")
dfs[is.na(dfs)] <- 0
dfs[dfs$author_unique == "hume, david (1560-1630)","highlight"] <- FALSE
dfs$size <- 2 + 1*as.numeric(dfs$highlight)

theme_set(theme_bw(20))
p <- ggplot(dfs, aes(x = folio, y = octavo)) +
       geom_text(aes(label = author_unique, color = highlight, size = size)) +       
       xlab("Folio") + ylab("Octavo") +
       guides(color = "none", size = "none") + 
       scale_color_manual(values = c("darkgray", "black")) +
       xlim(-20,max(dfs$folio) + 8) +
       scale_size(range = c(4,7))       
print(p)
```


```{r 20151023LIBER-4, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=6}
theme_set(theme_bw(20))
dfs <- df
#dfs$gatherings <- harmonize_names(dfs$gatherings, gatherings_table(),
#	       	  		  from = "Standard", to = "Name")$name
#dfs <- dfs %>% filter(gatherings %in% c("folio", "octavo"))
dfs <- dfs %>% filter(author_unique %in% topa) %>%
       	   filter(!is.na(author_birth) & !is.na(author_death))
dfs <- dfs %>%
       	        group_by(author_unique) %>%
	        summarize(titles = n(),
	        paper = sum(paper.consumption.km2, na.rm = T))
dfs$highlight <- rep("darkgray", nrow(dfs))
dfs$highlight[dfs$author_unique %in% selected.authors] <- "black"
p <- ggplot(dfs, aes(x = titles, y = paper, color = highlight)) 
p <- p + geom_text(aes(label = author_unique)) 
p <- p + scale_color_manual(values = c("darkgray", "black")) 
p <- p + guides(color = "none") 
p <- p + xlim(c(-50, 180)) 
p <- p + xlab("Title count") 
p <- p + ylab("Paper consumption (km2)")
       
print(p)	 
```




```{r 20151023LIBER-5, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=5}
theme_set(theme_bw(20))
dfs <- df %>% filter(author_gender == "female")
dfs <- dfs[-c(grep("jean", dfs$author_unique), grep("pierre", dfs$author_unique)),]
p <- top_plot(dfs, "author_unique", ntop = 20)
p <- p + scale_fill_manual(values = "black")
p <- p + guides(fill = "none")
p <- p + ylab("Title count")
print(p)	 
```



```{r 20151023LIBER-6, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=5}
theme_set(theme_bw(20))
p <- top_plot(df, "publication_place", ntop = 20)
p <- p + scale_fill_manual(values = "black")
p <- p + guides(fill = "none")
p <- p + ylab("Title count (Log scale)")
p <- p + scale_y_log10()
print(p)	 
```



```{r 20151023LIBER-8, echo=FALSE, message=FALSE, cache=FALSE, fig.height=6, fig.width=8}
theme_set(theme_bw(20))
top <- names(rev(sort(table(df$publication_place))))[1:50]
dfs <- df %>% filter(publication_place %in% top) %>% group_by(publication_place) %>% summarize(titles = n(), paper = sum(paper.consumption.km2, na.rm = T))
dfs$country <- get_country(dfs$publication_place)$country
dfs$usa <- dfs$country == "USA"
p <- ggplot(dfs, aes(x = log10(titles), y = log10(paper)))
p <- p + geom_text(aes(label = publication_place, color = usa), size = 5)
p <- p + xlim(c(1.2, log10(max(na.omit(dfs$titles[!is.infinite(dfs$titles)])))))
p <- p + xlab("Title Count") + ylab("Paper consumption (km2)")
p <- p + scale_color_manual(values = c("darkgray", "black"))
p <- p + guides(color = "none")
print(p)	 
```




```{r 20151023LIBER-10a, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=8}
library(sorvi)
dfs <- df %>% filter(publication_year >= 1470) %>% 
         group_by(publication_year) %>%
         summarize(titles = n(), paper = sum(paper.consumption.km2, na.rm = T))
	 
p1 <- regression_plot(titles ~ publication_year, data = dfs)
p1 <- p1 + xlab("Publication Year") + ylab("Title Count") 
p1 <- p1 + theme(axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15))
p1 <- p1 + theme(axis.title.x = element_text(size = 15), axis.title.y = element_text(size = 15))
p1 <- p1 + guides(fill = "none", alpha = "none")
print(p1)
```

```{r 20151023LIBER-10b, echo=FALSE, message=FALSE, cache=FALSE, fig.height=5, fig.width=8}
p2 <- regression_plot(paper ~ publication_year, data = dfs) +
       xlab("Publication Year") +
       ylab("Paper Consumption (km2)") 
p2 <- p2 + theme(axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15))
p2 <- p2 + theme(axis.title.x = element_text(size = 15), axis.title.y = element_text(size = 15))
p2 <- p2 + guides(fill = "none", alpha = "none")
print(p2)
```


```{r 20151023LIBER-11, echo=FALSE, message=FALSE, cache=FALSE, fig.height=4, fig.width=8}
theme_set(theme_bw(20))
library(sorvi)
dfs <- df %>% filter(publication_year >= 1470) %>% 
         group_by(publication_year) %>%
         summarize(paper.per.doc = mean(paper.consumption.km2, na.rm = T))

p <- ggplot(dfs, aes(y = paper.per.doc, x = publication_year)) +
       geom_line() + geom_point() +
       #geom_bar(stat = "identity") +
       xlab("Publication Year") + ylab("Paper per document")

print(p)
```

## How does publishing change ?

```{r 20151023LIBER-12, echo=FALSE, message=FALSE, cache=FALSE, fig.height=6, fig.width=9}
df2 <- df
df2$document.type <- rep(NA, nrow(df2))
df2$document.type[df2$pagecount > 32] <- "book"
df2$document.type[df2$pagecount <= 32] <- "pamphlet"
df2 <- df2[which(!is.na(df2$document.type)),]
df2$document.type <- factor(df2$document.type)
df2 <- df2 %>% group_by(publication_year, document.type) %>% summarize(paper.consumption.km2 = sum(paper.consumption.km2, na.rm = TRUE), n = n()) 
p <- ggplot(df2, aes(x = publication_year, y = paper.consumption.km2, group = document.type, color = document.type))
p <- p + geom_point()
p <- p + geom_smooth(method = "loess")
p <- p + ggtitle("Paper consumption per document type")
p <- p + xlab("Year")
p <- p + ylab("Paper consumption (km2)")
print(p)
```


```{r 20151023LIBER-13, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=7}
df2 <- df %>% group_by(publication_year, gatherings) %>% summarize(paper.consumption.km2 = sum(paper.consumption.km2, na.rm = TRUE), n = n()) 
df2 <- filter(df2, gatherings %in% setdiff(names(which(table(df2$gatherings) >= 50)), "NA"))
p <- ggplot(df2, aes(y = paper.consumption.km2, x = publication_year, group = gatherings, color = gatherings))
p <- p + geom_point()
p <- p + geom_smooth(method = "loess", size = 1)
p <- p + ggtitle("Annual paper consumption by gatherings")
p <- p + xlab("Year")
p <- p + ylab("Paper consumption (km2)")
print(p)
```


```{r 20151023LIBER-14, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=7}
# Compare to overall publication stats
# 1470 - 1790
library(gdata)
pubstat <- read.xls("data/Copy\ of\ simons-ESTC-1477-1800.xlsx")

# Remove duplicated titles
tmp <- df[, c("publication_year", "title")]
tmp <- tmp[!duplicated(tmp), ]
pubyears.history <- table(tmp$publication_year)

years <- 1470:1799
dff <- data.frame(list(year = years, 
              ESTC.yearly = pubstat$ESTC.yearly[match(years, pubstat$Year)],
	      ESTC.history = as.numeric(pubyears.history[match(years, names(pubyears.history))])))
dff$decade <- round(dff$year, -1)

library(reshape)
dfm <- melt(dff, id = c("year", "decade"))
dfi <- aggregate(dfm[, "value"], by = dfm[, c("variable", "decade")], sum)
dfi$documents.total <- dfi$x
dfi$documents.annual <- dfi$x/10
theme_set(theme_bw(20))
p <- ggplot(dfi, aes(x = decade, y = documents.annual, color = variable))
p <- p + geom_line() + geom_point()
p <- p + xlab("Year") + ylab("Publications per year")
p <- p + ggtitle("Publication activity 1470-1800")
p <- p + scale_color_manual(values=c("#CC6666", "#9999CC"))
p <- p + geom_point(data= dfm, aes(x = year, y = value, color = variable))

print(p)
```



```{r 20151023LIBER-15, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=7}
library(reshape)
dfm <- melt(dff, id = c("year", "decade"))
dfi <- aggregate(dfm[, "value"], by = dfm[, c("variable", "decade")], sum)
dfi$documents.total <- dfi$x
dfi$documents.annual <- dfi$x/10
theme_set(theme_bw(20))
p <- ggplot(dfi, aes(x = decade, y = x, shape = variable))
p <- p + geom_point(size = 4) + geom_smooth(size = 1, color = "black")
p <- p + xlab("Year") + ylab("Publications per decade")
p <- p + ggtitle("Publication activity 1470-1800")
p <- p + scale_color_manual(values=c("#CC6666", "#9999CC"))
p <- p + guides(shape = "none", color = "none")
p2 <- p
print(p2)
print(p)
```


```{r 20151023LIBER-16, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=7}

dfc <- data.frame(list(year = years))
dfc$decade <- round(dfc$year, -1) 
for (ctr in c("England", "Scotland", "USA")) {
  dfs <- subset(df, publication_country == ctr)
  tmp <- dfs[, c("publication_year", "title")]
  tmp <- tmp[!duplicated(tmp), ]
  dfc[[paste(ctr, "annual", sep = "-")]] <- table(tmp$publication_year)[as.character(years)]
}
dfcm <- melt(dfc, id = c("year", "decade"))

for (varname in unique(dfcm$variable)) {
  dfci <- aggregate(dfcm[, "value"], by = dfcm[, c("variable", "decade")], sum)
  dfci$documents.total <- dfci$x
  dfci$documents.annual <- dfci$x/10
}

mydf <- rbind(dfi, dfci)
theme_set(theme_bw(20))
mydf <- subset(mydf, !variable == "ESTC.yearly")
p <- ggplot(mydf, aes(x = decade, y = documents.annual, color = variable))
p <- p + geom_line() + geom_point()
p <- p + xlab("Year") + ylab("Publications per year")
p <- p + ggtitle("Publication activity 1470-1800")
print(p)
```

