---
title: "Summaries on North America"
author: "Leo Lahti"
date: "05/03/2016"
output: markdown_document
---

Read the preprocessed ESTC data table and load tools:

```{r, echo=FALSE, message=FALSE}
# Load libraries
library(ggplot2, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(reshape)
library(estc)
library(bibliographica)
```


```{r NAread}
# Complete data
df <- read.csv(file = "estc.csv", sep = "|")

# Pick USA documents only
country <- "USA"
df <- filter(df, publication.country == country)
```

We have `r nrow(df)` documents from `r country`.


## Most common authors from `r country`

```{r NAtopauth}
p <- top_plot(df, "author.unique", 20)
p <- p + ggtitle(paste("Most common authors from", country))
p <- p + ylab("Documents") + xlab("")
print(p)
```


## Top titles 

```{r NAtoptitles, fig.width=20, fig.height=10}
p <- top_plot(df, "publication.title", 20)
p <- p + ggtitle(paste("Most common titles from", country))
p <- p + ylab("Documents") + xlab("")
print(p)
```



## Historical publication volumes for top-5 publication places

Average annual output for each decade is shown by lines, the actual annual document counts are shown by points. 

```{r NApubvols, echo=FALSE, fig.width=20, fig.height=10}
publications <- tapply(df$unity, list(df$publication.decade, df$publication.place), sum)
publications[is.na(publications)] <- 0 # Set NAs to 0
publications <- publications/10 # Instead of decadal sum, use average annual output 

publications.annual <- tapply(df$unity, list(df$publication.year, df$publication.place), sum)
publications.annual[is.na(publications.annual)] <- 0 # Set NAs to 0

# Keep only top-5 publication places (w.r.t. total volume)
top.places <- names(rev(sort(colSums(publications)))[1:5])
publications <- publications[, top.places]
publications.annual <- publications.annual[, top.places]

dfm <- melt(publications) 
names(dfm) <- c("Time", "Place", "Documents")

dfm.annual <- melt(publications.annual) 
names(dfm.annual) <- c("Time", "Place", "Documents")

theme_set(theme_bw(20))
p <- ggplot(dfm, aes(x = Time, y = Documents, color = Place))
p <- p + geom_line() + geom_point()
p <- p + xlab("Year") + ylab("Publications per year")
p <- p + ggtitle(paste("Publication activity ", min(dfm$Time), "-", max(dfm$Time), sep = ""))
p <- p + scale_color_manual(values=c("red", "blue", "darkgreen", "black", "pink"))
p <- p + geom_point(data = dfm.annual, aes(x = Time, y = Documents, color = Place))
print(p)
```









