---
title: "Princeton summary"
author: "Leo Lahti"
date: "`r Sys.Date()`"
output: markdown_document
---

# Princeton summaries

Read the preprocessed ESTC data table and load tools:

```{r PrincetonInit, echo=FALSE, message=FALSE}
# Load libraries
library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape)
library(estc)
library(bibliographica)
```


```{r princeton, echo=FALSE, fig.width=10, fig.height=5}
# Complete data
#dfo <- read.csv(file = "estc.csv", sep = "|")
df <- df.preprocessed
selected.topics <- c("Thirty Years' War, 1618-1648", "Popish Plot, 1678")
dfs <- filter(df, subject.topic %in% selected.topics)
   
dfs <- dfs %>% group_by(subject.topic, publication.decade) %>% summarize(paper = sum(paper.consumption.km2, na.rm = TRUE), documents = n())

theme_set(theme_bw(20))
p <- ggplot(dfs, aes(x = publication.decade, y = documents, group = subject.topic))
p <- p + geom_point(aes(col = subject.topic))
p <- p + geom_line(aes(col = subject.topic))
p <- p + xlab("Publication Decade")
p <- p + ylab("Documents (n)")
p1 <- p

p <- ggplot(dfs, aes(x = publication.decade, y = paper, group = subject.topic))
p <- p + geom_point(aes(col = subject.topic))
p <- p + geom_line(aes(col = subject.topic))
p <- p + xlab("Publication Decade")
p <- p + ylab("Paper (km2)")
p2 <- p

library(gridExtra)
grid.arrange(p1, p2, nrow = 2)

```


```{r princeton2, echo=FALSE, fig.width=10, fig.height=5, warning=FALSE, message=FALSE}
#selected.countries <- c("England", "Ireland", "Scotland", "Wales")
selected.countries <- c("France", "Netherlands", "Germany", "Swizerland", "Belgium")
dfs <- filter(df, publication.country %in% selected.countries)
dfs <- dfs %>% filter(!is.na(publication.country))
dfs$publication.country <- droplevels(dfs$publication.country)

dfs <- dfs %>% group_by(publication.country, publication.decade) %>% summarize(paper = sum(paper.consumption.km2, na.rm = TRUE), documents = n())
theme_set(theme_bw(20))

p <- ggplot(dfs, aes(x = publication.decade, y = documents, group = publication.country))
p <- p + geom_point(aes(col = publication.country))
p <- p + geom_line(aes(col = publication.country))
p <- p + xlab("Publication Decade")
p <- p + ylab("Documents (n)")
p1 <- p

p <- ggplot(dfs, aes(x = publication.decade, y = paper, group = publication.country))
p <- p + geom_point(aes(col = publication.country))
p <- p + geom_line(aes(col = publication.country))
p <- p + xlab("Publication Decade")
p <- p + ylab("Paper (km2)")
p2 <- p

library(gridExtra)
grid.arrange(p1, p2, nrow = 2)
```


