---
title: "Shakespeare and Cervantes"
author: "Leo Lahti and Mikko Tolonen"
date: "18/04/2016"
output: markdown_document
---

Title count:

* Shakespeare: `r nraw[["Shakespeare"]]` total; `r nrow(tabs$Shakespeare)` accepted
* Cervantes:   `r nraw[["Cervantes"]]` total; `r nrow(tabs$Cervantes)` accepted


```{r shakespeare-versusother, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=8, fig.height=3, out.width="800px"}
# Shakespeare / Cervantes fractions of overall title count
# as function of time
dfs <- df.preprocessed
auth <- "Shakespeare"
d <- NULL
  dfs$author2 <- dfs$author %in% my.authors[[auth]]
  d <- dfs %>% group_by(publication_decade) %>%
	 summarize(freq = 100 * mean(author2, na.rm = T),
	 	   author = auth,
		   n = sum(author2, na.rm = T)
	 )
d$author <- factor(d$author)

# Visualize timeline
p <- ggplot(d, aes(x = publication_decade, y = freq)) +
       #geom_bar(stat = "identity", position = "stack", color = "black") +
       geom_line() +
       geom_point(aes(size = n)) +              
       xlab("Publication Decade") +
       ylab("Fraction of all titles (%)") +
       scale_fill_grey() +
       guides(fill = guide_legend("Author")) +
       ggtitle("Relative publishing activity")
print(p)
```


```{r shakespeare-tragedyvscomedy, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=8, fig.height=3, out.width="800px"}
auth <- "Shakespeare"
df <- tabs[[auth]]
df$publication_decade <- floor(df$publication_year/10) * 10 # 1790: 1790-1799
types = c("Tragedy", "Comedy", "History")
dfs <- df %>% filter(type %in% types) %>%
              group_by(publication_decade, type) %>%
              tally()
dfs$type <- factor(dfs$type, levels = types)
# Visualize the timeline
theme_set(theme_bw(20))
p <- ggplot(dfs, aes(x = publication_decade, y = n, fill = type)) +
       geom_bar(stat = "identity", position = "stack", color = "black") +
       xlab("Publication Decade") +
       ylab("Title Count") +
       scale_fill_grey() +
       guides(fill = guide_legend("Category")) +
       ggtitle(paste(auth, "Book categories"))       
print(p)
```



### Title popularity


```{r shakespeare-titles, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.show="hold", out.width="400px", fig.height=13, fig.width=6}
for (auth in names(my.authors)) {
  p <- top_plot(tabs[[auth]], "title", ntop = length(unique(tabs[[auth]]$title)))
  p <- p + ggtitle(auth) + ylab("Title count")
  print(p)
}
```



```{r shakespeare-titles2, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, out.width="800px", fig.height=5, fig.width=5}
df1 <- filter(tabs$Shakespeare, title %in% c("Hamlet", "Romeo and Juliet", "Macbeth", "Othello"))
df2 <- filter(tabs$Cervantes, title %in% "Don Quixote")
df <- rbind_all(list(df1, df2)) 

# Calculate relative abundances within each decade
dfs <- df %>% group_by(publication_decade, title) %>% tally()
dfs <- dfs %>% spread(title, n, fill = 0)
dfs[,-1] <- t(apply(dfs[, -1], 1, function(x) {x/sum(x)}))
dfs <- gather(dfs, publication_decade)
names(dfs) <- c("publication_decade", "title", "freq")
dfs$title <- factor(dfs$title, levels = unique(dfs$title))

dfs2 <- df %>% group_by(publication_decade, title) %>% tally()
p <- ggplot(dfs2, aes(x = publication_decade, y = n, color = title)) +
       geom_line() +
       #geom_smooth(method = "loess") +       
       geom_point() +       
       xlab("Publication Decade") +
       ylab("Title count (n)") +
       scale_fill_grey() +
       guides(color = guide_legend("Title")) +
       ggtitle("Comparison of popular titles")
print(p)

p <- ggplot(dfs, aes(x = publication_decade, y = 100*freq, fill = title)) +
       geom_bar(stat = "identity", position = "stack", color = "black") +
       xlab("Publication Decade") +
       ylab("Relative title count (%)") +
       scale_fill_grey() +
       guides(fill = guide_legend("Title")) +
       ggtitle("Comparison of popular titles")
print(p)
```


### Publisher timelines

```{r shakespeare-publisher, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, fig.width=8, fig.height=3, out.width="800px"}
auth <- "Shakespeare"
df <- tabs[[auth]]
#top.publishers <- names(which(top(df, "publisher") >= 20))
top.publishers <- names(top(df, "publisher", 5))

dfs <- df %>% group_by(publication_decade, publisher) %>%
              filter(publisher %in% top.publishers) %>% tally()

p <- ggplot(dfs, aes(x = publication_decade, y = n, fill = publisher)) +
       geom_bar(stat = "identity", position = "stack", color = "black") +
       xlab("Publication Decade") +
       ylab("Title Count") +
       scale_fill_grey() +
       guides(fill = guide_legend("Publisher")) +       
       ggtitle(paste(auth, ": publisher timelines", sep = ""))       

print(p)
```


